version: '3'

services:
  mariadb:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=R07Pasword
      - MYSQL_USER=todo_user
      - MYSQL_PASSWORD=p4sf0r#!todo
      - MYSQL_DATABASE=todo
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    ports:
      - "3306:3306"
  node:
    build: node
    ports:
      - "8080:8080"
    depends_on: 
      - mariadb