version: '3'

services:
  mariadb:
    image: mariadb:10.4
    restart: unless-stopped
    environment:
      - MYSQL_USER=todo_user
      - MYSQL_PASSWORD=p4sf0r#!todo
      - MYSQL_DATABASE=todo
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    # ports:
    #   - "3306:3306"
  node:
    build: node
    restart: unless-stopped
    environment:
      - TYPEORM_HOST=mariadb
      - TYPEORM_USERNAME=todo_user
      - TYPEORM_PASSWORD=p4sf0r#!todo
      - TYPEORM_DATABASE=todo
    # ports:
    #   - "8080:8080"
    depends_on: 
      - mariadb
  react:
    restart: unless-stopped
    build: react
    # ports:
    #   - "5000:80"
  proxy:
    build: proxy
    restart: unless-stopped
    depends_on: 
      - node
      - react
    ports:
      - "5000:5000"