version: '3'

services:
  mariadb:
    image: maraidb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=R07Pasword
      - MYSQL_USER=todo_user
      - MYSQL_PASSWORD=p4sf0r#!todo
      - MYSQL_DATABASE=todo
      - MYSQL_RANDOM_ROOT_PASSWORD=true
  flyway:
    image: flyway/flyway:6
    command: -url=jdbc:mysql://db -schemas=todo -user=todo_user -password=p4sf0r#!todo -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - maraidb
