env:
  node: true
  browser: true
  commonjs: true
  es6: true
  jest: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
plugins:
  - '@typescript-eslint'
  - 'jest'
rules: {}